import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { useLanguage } from '@/components/LanguageContext';
import { useStrategyRecalibration } from '@/hooks/strategy/useStrategyRecalibration';
import {
  Rocket, Package, CheckCircle2, FileText, Target, Brain,
  TrendingUp, Lightbulb, Users, RefreshCw, Download, ArrowRight
} from 'lucide-react';
import { toast } from 'sonner';

const HANDOFF_CHECKLIST = [
  { id: 'lessons', label: { en: 'Lessons Learned Package', ar: 'حزمة الدروس المستفادة' }, icon: Lightbulb },
  { id: 'recommendations', label: { en: 'Strategic Recommendations', ar: 'التوصيات الاستراتيجية' }, icon: Target },
  { id: 'patterns', label: { en: 'Pattern Analysis Report', ar: 'تقرير تحليل الأنماط' }, icon: Brain },
  { id: 'baselines', label: { en: 'Updated Baselines', ar: 'خطوط الأساس المحدثة' }, icon: TrendingUp },
  { id: 'stakeholder', label: { en: 'Stakeholder Feedback Summary', ar: 'ملخص ملاحظات أصحاب المصلحة' }, icon: Users },
  { id: 'improvements', label: { en: 'Methodology Improvements', ar: 'تحسينات المنهجية' }, icon: FileText }
];

export default function NextCycleInitializer({ planId, planName }) {
  const { t, language } = useLanguage();
  const { feedbackData, patterns, prepareNextCycle, isProcessing } = useStrategyRecalibration(planId);
  
  const [checklist, setChecklist] = useState({});
  const [nextCyclePackage, setNextCyclePackage] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const completedItems = Object.values(checklist).filter(Boolean).length;
  const progress = (completedItems / HANDOFF_CHECKLIST.length) * 100;

  const toggleCheckItem = (id) => {
    setChecklist(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const generatePackage = async () => {
    setIsGenerating(true);
    try {
      const pkg = await prepareNextCycle();
      setNextCyclePackage(pkg);
      toast.success(t({ en: 'Next cycle package generated', ar: 'تم إنشاء حزمة الدورة القادمة' }));
    } catch (error) {
      toast.error(t({ en: 'Failed to generate package', ar: 'فشل في إنشاء الحزمة' }));
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPackage = () => {
    if (!nextCyclePackage) return;

    const content = `# Next Cycle Strategic Intelligence Package
## Generated: ${new Date(nextCyclePackage.generatedAt).toLocaleDateString()}
## Plan: ${planName || planId}

---

## Strategic Recommendations

${nextCyclePackage.strategicRecommendations?.map((rec, i) => `
### ${i + 1}. ${rec.title}
- **Priority:** ${rec.priority}
- **Target Phase:** Phase ${rec.targetPhase}
- **Description:** ${rec.description}
`).join('\n') || 'No recommendations available.'}

---

## Key Patterns Identified

${nextCyclePackage.topPatterns?.map((p, i) => `${i + 1}. **${p.theme}** (${p.count} occurrences)`).join('\n') || 'No patterns identified.'}

---

## Evaluation Summary

- **Average Score:** ${nextCyclePackage.evaluationSummary?.avgScore?.toFixed(1) || 'N/A'}
- **Total Evaluations:** ${nextCyclePackage.evaluationSummary?.totalEvaluations || 0}

---

## Top Lessons Learned

${nextCyclePackage.lessonsLearned?.slice(0, 10).map((lesson, i) => `
### Lesson ${i + 1}
- **Category:** ${lesson.category || 'General'}
- **Lesson:** ${lesson.lesson}
- **Recommendation:** ${lesson.recommendation}
- **Source:** ${lesson.source_name}
`).join('\n') || 'No lessons recorded.'}

---

## Pre-Planning Intelligence Brief

Based on the analysis of the current strategic cycle, the following areas require attention in the next cycle:

1. Review and update baseline metrics using lessons from completed initiatives
2. Conduct fresh stakeholder analysis to capture new actors and changed priorities
3. Update environmental scan to reflect current market and policy landscape
4. Refine methodology based on identified improvement areas

---

*This package was automatically generated by the Strategy Recalibration System.*
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `next-cycle-package-${planId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Rocket className="h-5 w-5 text-primary" />
          {t({ en: 'Next Cycle Initializer', ar: 'مهيئ الدورة القادمة' })}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Progress Overview */}
        <div className="p-4 bg-primary/5 rounded-lg">
          <div className="flex items-center justify-between mb-2">
            <span className="font-medium">
              {t({ en: 'Handoff Preparation Progress', ar: 'تقدم إعداد التسليم' })}
            </span>
            <span className="text-sm text-muted-foreground">
              {completedItems}/{HANDOFF_CHECKLIST.length}
            </span>
          </div>
          <Progress value={progress} className="h-2" />
        </div>

        {/* Checklist */}
        <div className="space-y-3">
          <h3 className="font-medium">{t({ en: 'Handoff Checklist', ar: 'قائمة مراجعة التسليم' })}</h3>
          {HANDOFF_CHECKLIST.map((item) => {
            const Icon = item.icon;
            return (
              <label
                key={item.id}
                className={`flex items-center gap-3 p-3 border rounded-lg cursor-pointer transition-colors ${
                  checklist[item.id] ? 'bg-green-50 border-green-200' : 'hover:bg-muted/50'
                }`}
              >
                <Checkbox
                  checked={checklist[item.id] || false}
                  onCheckedChange={() => toggleCheckItem(item.id)}
                />
                <Icon className={`h-4 w-4 ${checklist[item.id] ? 'text-green-600' : 'text-muted-foreground'}`} />
                <span className={checklist[item.id] ? 'text-green-900' : ''}>
                  {t(item.label)}
                </span>
                {checklist[item.id] && (
                  <CheckCircle2 className="h-4 w-4 text-green-600 ml-auto" />
                )}
              </label>
            );
          })}
        </div>

        {/* Data Summary */}
        <div className="grid grid-cols-3 gap-3">
          <div className="p-3 bg-muted rounded-lg text-center">
            <p className="text-2xl font-bold text-primary">{feedbackData.lessons?.length || 0}</p>
            <p className="text-xs text-muted-foreground">{t({ en: 'Lessons', ar: 'الدروس' })}</p>
          </div>
          <div className="p-3 bg-muted rounded-lg text-center">
            <p className="text-2xl font-bold text-primary">{patterns.patterns?.length || 0}</p>
            <p className="text-xs text-muted-foreground">{t({ en: 'Patterns', ar: 'الأنماط' })}</p>
          </div>
          <div className="p-3 bg-muted rounded-lg text-center">
            <p className="text-2xl font-bold text-primary">{patterns.recommendations?.length || 0}</p>
            <p className="text-xs text-muted-foreground">{t({ en: 'Recommendations', ar: 'التوصيات' })}</p>
          </div>
        </div>

        {/* Generate Package */}
        {!nextCyclePackage ? (
          <Button 
            onClick={generatePackage}
            disabled={isGenerating || completedItems < 3}
            className="w-full"
          >
            {isGenerating ? (
              <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <Package className="h-4 w-4 mr-2" />
            )}
            {t({ en: 'Generate Next Cycle Package', ar: 'إنشاء حزمة الدورة القادمة' })}
          </Button>
        ) : (
          <div className="space-y-4">
            <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle2 className="h-5 w-5 text-green-600" />
                <span className="font-medium text-green-900">
                  {t({ en: 'Package Ready', ar: 'الحزمة جاهزة' })}
                </span>
              </div>
              <p className="text-sm text-green-800">
                {t({ 
                  en: 'The next cycle intelligence package has been generated with all available data.',
                  ar: 'تم إنشاء حزمة المعلومات للدورة القادمة مع جميع البيانات المتاحة.'
                })}
              </p>
            </div>

            {/* Package Summary */}
            <div className="space-y-2">
              <h4 className="font-medium text-sm">{t({ en: 'Package Contents', ar: 'محتويات الحزمة' })}</h4>
              <div className="grid grid-cols-2 gap-2 text-sm">
                <div className="p-2 bg-muted rounded flex justify-between">
                  <span>{t({ en: 'Recommendations', ar: 'التوصيات' })}</span>
                  <Badge variant="secondary">{nextCyclePackage.strategicRecommendations?.length || 0}</Badge>
                </div>
                <div className="p-2 bg-muted rounded flex justify-between">
                  <span>{t({ en: 'Lessons', ar: 'الدروس' })}</span>
                  <Badge variant="secondary">{nextCyclePackage.lessonsLearned?.length || 0}</Badge>
                </div>
                <div className="p-2 bg-muted rounded flex justify-between">
                  <span>{t({ en: 'Patterns', ar: 'الأنماط' })}</span>
                  <Badge variant="secondary">{nextCyclePackage.topPatterns?.length || 0}</Badge>
                </div>
                <div className="p-2 bg-muted rounded flex justify-between">
                  <span>{t({ en: 'Avg Score', ar: 'متوسط النتيجة' })}</span>
                  <Badge variant="secondary">{nextCyclePackage.evaluationSummary?.avgScore?.toFixed(1) || 'N/A'}</Badge>
                </div>
              </div>
            </div>

            <div className="flex gap-3">
              <Button variant="outline" onClick={() => setNextCyclePackage(null)} className="flex-1">
                <RefreshCw className="h-4 w-4 mr-2" />
                {t({ en: 'Regenerate', ar: 'إعادة الإنشاء' })}
              </Button>
              <Button onClick={downloadPackage} className="flex-1">
                <Download className="h-4 w-4 mr-2" />
                {t({ en: 'Download Package', ar: 'تحميل الحزمة' })}
              </Button>
            </div>
          </div>
        )}

        {/* Handoff to Phase 1 */}
        <div className="pt-4 border-t">
          <div className="flex items-center gap-3 p-4 bg-primary/5 rounded-lg">
            <Rocket className="h-8 w-8 text-primary" />
            <div>
              <p className="font-medium">
                {t({ en: 'Ready for Next Cycle?', ar: 'جاهز للدورة القادمة؟' })}
              </p>
              <p className="text-sm text-muted-foreground">
                {t({ 
                  en: 'When ready, initiate Phase 1 pre-planning with the generated intelligence package.',
                  ar: 'عندما تكون جاهزاً، ابدأ المرحلة 1 للتخطيط المسبق مع حزمة المعلومات المُنشأة.'
                })}
              </p>
            </div>
            <ArrowRight className="h-5 w-5 text-primary ml-auto" />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
