import {
  LayoutDashboard,
  AlertCircle,
  Lightbulb,
  TestTube,
  Microscope,
  TrendingUp,
  BarChart3,
  Users,
  CheckCircle,
  FileText,
  Building2,
  Activity,
  Rocket,
  Award,
  Shield,
  Target,
  Sparkles,
  BookOpen,
  Globe,
  User,
  Handshake,
  Calendar,
  Bell,
  MessageSquare,
  Map,
  Briefcase,
  GraduationCap,
  Clock,
  FileBarChart,
  ScrollText,
  Wallet,
  History,
  DollarSign,
  UserCheck,
  Inbox,
  Database,
  Settings,
  FolderKanban,
  ClipboardList,
  Layers,
  Scale,
  Network,
  FileSearch,
  Newspaper,
  Gift,
  UserCircle,
  Star,
  PieChart,
  Gauge,
  LayoutGrid,
  Workflow,
  Image,
  Palette,
  Tags,
  ToggleLeft,
  Link2,
  Mail,
  Brain,
  LineChart,
  Compass,
  FlaskConical,
  Cpu,
  Home
} from 'lucide-react';

// Common home link that appears at top of all persona sidebars
const HOME_LINK = { name: 'PublicPortal', icon: Home, label: { en: 'Home', ar: 'الرئيسية' }, isExternal: true, path: '/' };

// Flat menu configurations per persona
// Note: Profile and Settings are in the header dropdown, not sidebar
export const SIDEBAR_MENUS = {
  admin: {
    label: { en: 'Platform Admin', ar: 'مدير المنصة' },
    icon: Shield,
    color: 'from-red-600 to-rose-500',
    items: [
      HOME_LINK,
      { name: 'Home', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'UserManagementHub', icon: Users, label: { en: 'Users', ar: 'المستخدمين' } },
      { name: 'RolePermissionManager', icon: UserCheck, label: { en: 'Roles & Permissions', ar: 'الأدوار والصلاحيات' } },
      { name: 'RBACHub', icon: Shield, label: { en: 'RBAC Dashboard', ar: 'لوحة الصلاحيات' } },
      { name: 'ApprovalCenter', icon: CheckCircle, label: { en: 'Approvals', ar: 'الموافقات' } },
      { name: 'DataManagementHub', icon: Database, label: { en: 'Data Management', ar: 'إدارة البيانات' } },
      { name: 'BulkDataOperations', icon: Layers, label: { en: 'Bulk Operations', ar: 'العمليات الجماعية' } },
      { name: 'ExpertRegistry', icon: GraduationCap, label: { en: 'Expert Registry', ar: 'سجل الخبراء' } },
      { name: 'MenuRBACCoverageReport', icon: FileBarChart, label: { en: 'Coverage Reports', ar: 'تقارير التغطية' } },
      { name: 'ValidationDashboard', icon: ClipboardList, label: { en: 'Journey Analysis', ar: 'تحليل الرحلة' } },
      { name: 'MediaLibrary', icon: Image, label: { en: 'Media Library', ar: 'مكتبة الوسائط' } },
      { name: 'BrandingSettings', icon: Palette, label: { en: 'Branding Settings', ar: 'إعدادات العلامة' } },
      { name: 'TaxonomyBuilder', icon: Tags, label: { en: 'Taxonomy Builder', ar: 'منشئ التصنيف' } },
      { name: 'FeatureFlagsDashboard', icon: ToggleLeft, label: { en: 'Feature Flags', ar: 'أعلام الميزات' } },
      { name: 'IntegrationManager', icon: Link2, label: { en: 'Integration Manager', ar: 'مدير التكامل' } },
      { name: 'EmailTemplateEditor', icon: Mail, label: { en: 'Email Templates', ar: 'قوالب البريد' } },
      { name: 'Challenges', icon: AlertCircle, label: { en: 'Challenges', ar: 'التحديات' } },
      { name: 'Pilots', icon: TestTube, label: { en: 'Pilots', ar: 'التجارب' } },
      { name: 'Solutions', icon: Lightbulb, label: { en: 'Solutions', ar: 'الحلول' } },
      { name: 'Programs', icon: Calendar, label: { en: 'Programs', ar: 'البرامج' } },
      { name: 'Municipalities', icon: Building2, label: { en: 'Municipalities', ar: 'البلديات' } },
      { name: 'Organizations', icon: Briefcase, label: { en: 'Organizations', ar: 'المنظمات' } },
      { name: 'ReportsBuilder', icon: BarChart3, label: { en: 'Analytics', ar: 'التحليلات' } },
      { name: 'AuditTrail', icon: History, label: { en: 'Audit Logs', ar: 'سجلات التدقيق' } },
      { name: 'SystemHealthDashboard', icon: Activity, label: { en: 'System Health', ar: 'صحة النظام' } },
      { name: 'MenuSidebarComparison', icon: LayoutGrid, label: { en: 'Menu Comparison', ar: 'مقارنة القوائم' } },
    ]
  },

  executive: {
    label: { en: 'Executive / GDISB', ar: 'تنفيذي / الوكالة' },
    icon: Target,
    color: 'from-purple-600 to-violet-500',
    items: [
      HOME_LINK,
      { name: 'ExecutiveDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'StrategyCockpit', icon: Gauge, label: { en: 'Strategy Cockpit', ar: 'قمرة الاستراتيجية' } },
      { name: 'OKRManagementSystem', icon: Target, label: { en: 'OKR Management', ar: 'إدارة الأهداف' } },
      { name: 'Portfolio', icon: FolderKanban, label: { en: 'Portfolio Management', ar: 'إدارة المحفظة' } },
      { name: 'StrategicPlans', icon: FileBarChart, label: { en: 'Strategic Plans', ar: 'الخطط الاستراتيجية' } },
      { name: 'ExecutiveBriefGenerator', icon: FileText, label: { en: 'Brief Generator', ar: 'مولد الموجزات' } },
      { name: 'QuarterlyReviewWizard', icon: Calendar, label: { en: 'Quarterly Review', ar: 'المراجعة الربعية' } },
      { name: 'DecisionSimulator', icon: Scale, label: { en: 'Decision Simulator', ar: 'محاكي القرارات' } },
      { name: 'PredictiveForecastingDashboard', icon: Brain, label: { en: 'Predictive Forecasting', ar: 'التنبؤ المستقبلي' } },
      { name: 'CompetitiveIntelligenceDashboard', icon: LineChart, label: { en: 'Competitive Intelligence', ar: 'الذكاء التنافسي' } },
      { name: 'InternationalBenchmarkingSuite', icon: Compass, label: { en: 'International Benchmarking', ar: 'المقارنة الدولية' } },
      { name: 'Programs', icon: Calendar, label: { en: 'Programs Overview', ar: 'نظرة البرامج' } },
      { name: 'RDProjects', icon: Rocket, label: { en: 'R&D Overview', ar: 'نظرة البحث والتطوير' } },
      { name: 'Challenges', icon: AlertCircle, label: { en: 'Challenges', ar: 'التحديات' } },
      { name: 'Pilots', icon: TestTube, label: { en: 'Pilots', ar: 'التجارب' } },
      { name: 'PipelineHealthDashboard', icon: Activity, label: { en: 'Pipeline Health', ar: 'صحة الخط' } },
      { name: 'NationalInnovationMap', icon: Map, label: { en: 'Innovation Map', ar: 'خريطة الابتكار' } },
      { name: 'Municipalities', icon: Building2, label: { en: 'Municipalities', ar: 'البلديات' } },
      { name: 'ApprovalCenter', icon: CheckCircle, label: { en: 'Approvals', ar: 'الموافقات' } },
      { name: 'ReportsBuilder', icon: BarChart3, label: { en: 'Analytics & Reports', ar: 'التحليلات والتقارير' } },
    ]
  },

  deputyship: {
    label: { en: 'Deputyship', ar: 'الوكالة' },
    icon: Globe,
    color: 'from-indigo-600 to-blue-500',
    items: [
      HOME_LINK,
      { name: 'ExecutiveDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'RegionalDashboard', icon: Map, label: { en: 'Regional Dashboard', ar: 'لوحة إقليمية' } },
      { name: 'SectorDashboard', icon: PieChart, label: { en: 'Sector Dashboard', ar: 'لوحة القطاع' } },
      { name: 'MultiCityOrchestration', icon: Network, label: { en: 'Multi-City Orchestration', ar: 'تنسيق متعدد المدن' } },
      { name: 'CrossCityLearningHub', icon: BookOpen, label: { en: 'Cross-City Learning', ar: 'التعلم عبر المدن' } },
      { name: 'CapacityPlanning', icon: Cpu, label: { en: 'Capacity Planning', ar: 'تخطيط القدرات' } },
      { name: 'StrategicPlans', icon: Target, label: { en: 'Strategic Plans', ar: 'الخطط الاستراتيجية' } },
      { name: 'PolicyHub', icon: ScrollText, label: { en: 'Policy Hub', ar: 'مركز السياسات' } },
      { name: 'MIIDrillDown', icon: PieChart, label: { en: 'MII Drill Down', ar: 'تحليل المؤشر' } },
      { name: 'NationalInnovationMap', icon: Map, label: { en: 'National Overview', ar: 'النظرة الوطنية' } },
      { name: 'Municipalities', icon: Building2, label: { en: 'Municipalities', ar: 'البلديات' } },
      { name: 'Challenges', icon: AlertCircle, label: { en: 'Challenges', ar: 'التحديات' } },
      { name: 'Pilots', icon: TestTube, label: { en: 'Pilots', ar: 'التجارب' } },
      { name: 'Solutions', icon: Lightbulb, label: { en: 'Solutions', ar: 'الحلول' } },
      { name: 'Programs', icon: Calendar, label: { en: 'Programs', ar: 'البرامج' } },
      { name: 'ApprovalCenter', icon: CheckCircle, label: { en: 'Approvals', ar: 'الموافقات' } },
      { name: 'ReportsBuilder', icon: BarChart3, label: { en: 'Analytics', ar: 'التحليلات' } },
    ]
  },

  municipality: {
    label: { en: 'Municipality', ar: 'البلدية' },
    icon: Building2,
    color: 'from-emerald-600 to-green-500',
    items: [
      HOME_LINK,
      { name: 'MunicipalityDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' }, permission: 'dashboard_view', useMyMunicipality: true },
      { name: 'MunicipalityProfile', icon: Building2, label: { en: 'Municipality Profile', ar: 'ملف البلدية' }, permission: 'municipality_view', useMyMunicipality: true },
      { name: 'MIIDrillDown', icon: PieChart, label: { en: 'MII Score Details', ar: 'تفاصيل المؤشر' }, permission: 'mii_view', useMyMunicipality: true },
      { name: 'MunicipalityPeerMatcher', icon: Users, label: { en: 'Peer Benchmarking', ar: 'المقارنة المعيارية' }, permission: 'mii_view' },
      { name: 'ChallengeCreateWizard', icon: AlertCircle, label: { en: 'Create Challenge', ar: 'إنشاء تحدي' }, permission: 'challenge_create' },
      { name: 'PilotCreateWizard', icon: TestTube, label: { en: 'Create Pilot', ar: 'إنشاء تجربة' }, permission: 'pilot_create' },
      { name: 'MyChallenges', icon: AlertCircle, label: { en: 'My Challenges', ar: 'تحدياتي' }, permission: 'challenge_view' },
      { name: 'MyPilots', icon: TestTube, label: { en: 'My Pilots', ar: 'تجاربي' }, permission: 'pilot_view' },
      { name: 'Programs', icon: Calendar, label: { en: 'Programs', ar: 'البرامج' }, permission: 'program_view' },
      { name: 'LivingLabs', icon: FlaskConical, label: { en: 'Living Labs', ar: 'المختبرات الحية' }, permission: 'livinglab_view' },
      { name: 'MunicipalProposalInbox', icon: Inbox, label: { en: 'Proposals', ar: 'المقترحات' }, permission: 'proposal_view' },
      { name: 'Solutions', icon: Lightbulb, label: { en: 'Solutions', ar: 'الحلول' }, permission: 'solution_view' },
      { name: 'MyApprovals', icon: CheckCircle, label: { en: 'Approvals', ar: 'الموافقات' }, permission: 'approval_view' },
      { name: 'MunicipalityIdeasView', icon: Sparkles, label: { en: 'Citizen Ideas', ar: 'أفكار المواطنين' }, permission: 'idea_manage' },
      { name: 'Knowledge', icon: BookOpen, label: { en: 'Knowledge Hub', ar: 'مركز المعرفة' }, permission: 'knowledge_view' },
      { name: 'ContractManagement', icon: ScrollText, label: { en: 'Contracts', ar: 'العقود' }, permission: 'contract_view' },
      { name: 'BudgetManagement', icon: Wallet, label: { en: 'Budget', ar: 'الميزانية' }, permission: 'budget_view' },
      { name: 'TeamManagement', icon: Users, label: { en: 'Team', ar: 'الفريق' }, permission: 'user_manage', roles: ['municipality_admin', 'municipality_director', 'municipality_manager'] },
      { name: 'ReportsBuilder', icon: BarChart3, label: { en: 'Analytics', ar: 'التحليلات' }, permission: 'reports_view' },
    ]
  },

  provider: {
    label: { en: 'Provider', ar: 'المزود' },
    icon: Briefcase,
    color: 'from-orange-600 to-amber-500',
    items: [
      HOME_LINK,
      { name: 'StartupDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'SolutionCreateWizard', icon: Lightbulb, label: { en: 'Create Solution', ar: 'إنشاء حل' } },
      { name: 'ProviderPortfolioDashboard', icon: FolderKanban, label: { en: 'My Solutions', ar: 'حلولي' } },
      { name: 'StartupProfile', icon: Building2, label: { en: 'Company Profile', ar: 'ملف الشركة' } },
      { name: 'TeamManagement', icon: Users, label: { en: 'Team Members', ar: 'أعضاء الفريق' } },
      { name: 'FinancialsDashboard', icon: DollarSign, label: { en: 'Financials', ar: 'المالية' } },
      { name: 'OpportunityFeed', icon: Sparkles, label: { en: 'Opportunities', ar: 'الفرص' } },
      { name: 'MyChallengeTracker', icon: Target, label: { en: 'Challenge Tracker', ar: 'متتبع التحديات' } },
      { name: 'MyApplications', icon: FileText, label: { en: 'Applications', ar: 'الطلبات' } },
      { name: 'MyPilots', icon: TestTube, label: { en: 'My Pilots', ar: 'تجاربي' } },
      { name: 'ContractManagement', icon: ScrollText, label: { en: 'Contracts', ar: 'العقود' } },
      { name: 'MyPartnershipsPage', icon: Handshake, label: { en: 'Partnerships', ar: 'الشراكات' } },
      { name: 'Knowledge', icon: BookOpen, label: { en: 'Knowledge Hub', ar: 'مركز المعرفة' } },
      { name: 'Network', icon: Network, label: { en: 'Network', ar: 'الشبكة' } },
      { name: 'EventCalendar', icon: Calendar, label: { en: 'Events', ar: 'الفعاليات' } },
      { name: 'Programs', icon: Calendar, label: { en: 'Programs', ar: 'البرامج' } },
      { name: 'Messaging', icon: MessageSquare, label: { en: 'Messages', ar: 'الرسائل' } },
    ]
  },

  expert: {
    label: { en: 'Expert', ar: 'خبير' },
    icon: GraduationCap,
    color: 'from-amber-600 to-yellow-500',
    items: [
      HOME_LINK,
      { name: 'ExpertDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'ExpertProfile', icon: UserCircle, label: { en: 'My Profile', ar: 'ملفي الشخصي' } },
      { name: 'ExpertPerformanceDashboard', icon: Activity, label: { en: 'Performance', ar: 'الأداء' } },
      { name: 'ExpertPanelManagement', icon: LayoutGrid, label: { en: 'Panel Management', ar: 'إدارة اللجان' } },
      { name: 'EvaluationPanel', icon: CheckCircle, label: { en: 'Evaluations', ar: 'التقييمات' } },
      { name: 'ExpertAssignmentQueue', icon: Inbox, label: { en: 'My Assignments', ar: 'مهامي' } },
      { name: 'EvaluationHistory', icon: History, label: { en: 'Evaluation History', ar: 'سجل التقييمات' } },
      { name: 'PilotEvaluations', icon: TestTube, label: { en: 'Pilot Reviews', ar: 'مراجعات التجارب' } },
      { name: 'ExpertMatchingEngine', icon: Users, label: { en: 'Expert Network', ar: 'شبكة الخبراء' } },
      { name: 'CalendarView', icon: Calendar, label: { en: 'Calendar', ar: 'التقويم' } },
      { name: 'Knowledge', icon: BookOpen, label: { en: 'Knowledge Hub', ar: 'مركز المعرفة' } },
      { name: 'MyDeadlines', icon: Clock, label: { en: 'Deadlines', ar: 'المواعيد' } },
      { name: 'Messaging', icon: MessageSquare, label: { en: 'Messages', ar: 'الرسائل' } },
    ]
  },

  researcher: {
    label: { en: 'Researcher', ar: 'باحث' },
    icon: Microscope,
    color: 'from-teal-600 to-cyan-500',
    items: [
      HOME_LINK,
      { name: 'ResearcherDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'RDCalls', icon: Rocket, label: { en: 'R&D Calls', ar: 'دعوات البحث' } },
      { name: 'ResearchOutputsHub', icon: FileSearch, label: { en: 'Research Outputs', ar: 'مخرجات البحث' } },
      { name: 'AcademiaDashboard', icon: Building2, label: { en: 'Institution Dashboard', ar: 'لوحة المؤسسة' } },
      { name: 'FundingTracker', icon: DollarSign, label: { en: 'Funding Tracker', ar: 'متتبع التمويل' } },
      { name: 'Publications', icon: BookOpen, label: { en: 'Publications', ar: 'المنشورات' } },
      { name: 'ResearcherWorkspace', icon: Microscope, label: { en: 'Workspace', ar: 'مساحة العمل' } },
      { name: 'MyRDProjects', icon: TestTube, label: { en: 'My Projects', ar: 'مشاريعي' } },
      { name: 'RDProjects', icon: Rocket, label: { en: 'R&D Hub', ar: 'مركز البحث' } },
      { name: 'CollaborationHub', icon: Users, label: { en: 'Collaboration', ar: 'التعاون' } },
      { name: 'Knowledge', icon: BookOpen, label: { en: 'Knowledge Hub', ar: 'مركز المعرفة' } },
      { name: 'MyDeadlines', icon: Clock, label: { en: 'Deadlines', ar: 'المواعيد' } },
      { name: 'Messaging', icon: MessageSquare, label: { en: 'Messages', ar: 'الرسائل' } },
    ]
  },

  citizen: {
    label: { en: 'Citizen', ar: 'مواطن' },
    icon: Users,
    color: 'from-slate-600 to-gray-500',
    items: [
      HOME_LINK,
      { name: 'CitizenDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'CitizenIdeaSubmission', icon: Lightbulb, label: { en: 'Submit Idea', ar: 'إرسال فكرة' } },
      { name: 'ChallengeIdeaResponse', icon: Target, label: { en: 'Submit Proposal', ar: 'تقديم مقترح' } },
      { name: 'PublicIdeasBoard', icon: Sparkles, label: { en: 'Ideas Board', ar: 'لوحة الأفكار' } },
      { name: 'CitizenChallengesBrowser', icon: Target, label: { en: 'Browse Challenges', ar: 'تصفح التحديات' } },
      { name: 'CitizenSolutionsBrowser', icon: Lightbulb, label: { en: 'Browse Solutions', ar: 'تصفح الحلول' } },
      { name: 'CitizenLivingLabsBrowser', icon: FlaskConical, label: { en: 'Living Labs', ar: 'المختبرات الحية' } },
      { name: 'CitizenRewards', icon: Gift, label: { en: 'Rewards & Points', ar: 'المكافآت والنقاط' } },
      { name: 'PublicPilotTracker', icon: TestTube, label: { en: 'Public Pilots', ar: 'التجارب العامة' } },
      { name: 'CitizenPilotEnrollment', icon: UserCheck, label: { en: 'Pilot Enrollment', ar: 'التسجيل في التجارب' } },
      { name: 'EventCalendar', icon: Calendar, label: { en: 'Events', ar: 'الفعاليات' } },
      { name: 'News', icon: Newspaper, label: { en: 'News', ar: 'الأخبار' } },
      { name: 'CitizenLeaderboard', icon: Award, label: { en: 'Leaderboard', ar: 'المتصدرين' } },
    ]
  },

  // Generic authenticated user - defaults to citizen-like access
  user: {
    label: { en: 'User', ar: 'مستخدم' },
    icon: User,
    color: 'from-gray-600 to-slate-500',
    items: [
      { name: 'PublicPortal', icon: Home, label: { en: 'Home', ar: 'الرئيسية' }, path: '/' },
      { name: 'CitizenDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'CitizenIdeaSubmission', icon: Lightbulb, label: { en: 'Submit Idea', ar: 'إرسال فكرة' } },
      { name: 'ChallengeIdeaResponse', icon: Target, label: { en: 'Submit Proposal', ar: 'تقديم مقترح' } },
      { name: 'PublicIdeasBoard', icon: Sparkles, label: { en: 'Ideas Board', ar: 'لوحة الأفكار' } },
      { name: 'CitizenChallengesBrowser', icon: Target, label: { en: 'Browse Challenges', ar: 'تصفح التحديات' } },
      { name: 'CitizenSolutionsBrowser', icon: Lightbulb, label: { en: 'Browse Solutions', ar: 'تصفح الحلول' } },
      { name: 'CitizenLivingLabsBrowser', icon: FlaskConical, label: { en: 'Living Labs', ar: 'المختبرات الحية' } },
      { name: 'PublicPilotTracker', icon: TestTube, label: { en: 'Public Pilots', ar: 'التجارب العامة' } },
      { name: 'News', icon: Newspaper, label: { en: 'News', ar: 'الأخبار' } },
      { name: 'EventCalendar', icon: Calendar, label: { en: 'Events', ar: 'الفعاليات' } },
    ]
  },

  // Viewer - minimal authenticated access (browse only, cannot participate)
  viewer: {
    label: { en: 'Visitor', ar: 'زائر' },
    icon: User,
    color: 'from-gray-500 to-slate-400',
    items: [
      HOME_LINK,
      { name: 'ViewerDashboard', icon: LayoutDashboard, label: { en: 'Dashboard', ar: 'لوحة التحكم' } },
      { name: 'News', icon: Newspaper, label: { en: 'News', ar: 'الأخبار' } },
      { name: 'EventCalendar', icon: Calendar, label: { en: 'Events', ar: 'الفعاليات' } },
      { name: 'PublicIdeasBoard', icon: Lightbulb, label: { en: 'Ideas', ar: 'الأفكار' } },
      { name: 'PublicPilotTracker', icon: TestTube, label: { en: 'Pilots', ar: 'التجارب' } },
    ]
  }
};

export default SIDEBAR_MENUS;
