import React from 'react';
import { Button } from "@/components/ui/button";
import { FileText } from 'lucide-react';
import { toast } from 'sonner';

export default function PDFExport({ data, title, entityType }) {
  const generatePDF = () => {
    // Create HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; direction: ltr; }
          .rtl { direction: rtl; text-align: right; }
          h1 { color: #0f172a; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
          .header { background: linear-gradient(135deg, #3b82f6, #14b8a6); color: white; padding: 20px; margin-bottom: 20px; }
          .section { margin: 20px 0; padding: 15px; border: 1px solid #e2e8f0; border-radius: 8px; }
          .label { font-weight: bold; color: #475569; }
          .value { color: #0f172a; margin-left: 10px; }
          table { width: 100%; border-collapse: collapse; margin: 10px 0; }
          th, td { border: 1px solid #e2e8f0; padding: 8px; text-align: left; }
          th { background: #f1f5f9; font-weight: bold; }
          .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
          .status-approved { background: #d1fae5; color: #065f46; }
          .status-pending { background: #fef3c7; color: #92400e; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Saudi Innovates Platform | منصة الابتكار السعودي</h1>
          <p>Generated: ${new Date().toLocaleString()}</p>
        </div>
        
        <h1>${title}</h1>
        
        ${entityType === 'Challenge' ? renderChallenge(data) : 
          entityType === 'Pilot' ? renderPilot(data) : 
          renderGeneric(data)}
        
        <div class="section" style="margin-top: 40px; background: #f8fafc;">
          <p style="font-size: 12px; color: #64748b;">
            This report was automatically generated by Saudi Innovates Platform<br>
            National Municipal Innovation Platform – Ministry of Municipalities and Housing (MoMAH)
          </p>
        </div>
      </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}.html`;
    a.click();
    
    toast.success('PDF/HTML exported successfully');
  };

  const renderChallenge = (challenge) => `
    <div class="section">
      <p><span class="label">Code:</span><span class="value">${challenge.code}</span></p>
      <p><span class="label">Status:</span><span class="badge status-${challenge.status}">${challenge.status}</span></p>
      <p><span class="label">Sector:</span><span class="value">${challenge.sector}</span></p>
      <p><span class="label">Priority:</span><span class="value">${challenge.priority}</span></p>
    </div>
    
    <div class="section">
      <h2>Title</h2>
      <p>${challenge.title_en}</p>
      <p class="rtl">${challenge.title_ar || ''}</p>
    </div>
    
    <div class="section">
      <h2>Description</h2>
      <p>${challenge.description_en || ''}</p>
      <div class="rtl"><p>${challenge.description_ar || ''}</p></div>
    </div>
    
    ${challenge.kpis && challenge.kpis.length > 0 ? `
      <div class="section">
        <h2>KPIs</h2>
        <table>
          <tr><th>KPI</th><th>Baseline</th><th>Target</th></tr>
          ${challenge.kpis.map(kpi => `
            <tr><td>${kpi.name}</td><td>${kpi.baseline}</td><td>${kpi.target}</td></tr>
          `).join('')}
        </table>
      </div>
    ` : ''}
  `;

  const renderPilot = (pilot) => `
    <div class="section">
      <p><span class="label">Code:</span><span class="value">${pilot.code}</span></p>
      <p><span class="label">Stage:</span><span class="badge">${pilot.stage}</span></p>
      <p><span class="label">Duration:</span><span class="value">${pilot.duration_weeks} weeks</span></p>
      <p><span class="label">Budget:</span><span class="value">${pilot.budget} ${pilot.budget_currency}</span></p>
    </div>
    
    <div class="section">
      <h2>Title</h2>
      <p>${pilot.title_en}</p>
      <p class="rtl">${pilot.title_ar || ''}</p>
    </div>
  `;

  const renderGeneric = (item) => `
    <div class="section">
      <pre>${JSON.stringify(item, null, 2)}</pre>
    </div>
  `;

  return (
    <Button variant="outline" size="sm" onClick={generatePDF}>
      <FileText className="h-4 w-4 mr-2" />
      Export PDF
    </Button>
  );
}