-- Restore critical relationships by adding missing attributes/constraints
-- Generated by Antigravity

-- 1. Challenges -> Sectors
ALTER TABLE "public"."challenges"
ADD CONSTRAINT "challenges_sector_id_fkey"
FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("id");

-- 2. Programs -> Sectors
ALTER TABLE "public"."programs"
ADD CONSTRAINT "programs_sector_id_fkey"
FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("id");

-- 3. RD Projects -> Sectors
ALTER TABLE "public"."rd_projects"
ADD CONSTRAINT "rd_projects_sector_id_fkey"
FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("id");

-- 4. Knowledge Documents -> Sectors
ALTER TABLE "public"."knowledge_documents"
ADD CONSTRAINT "knowledge_documents_sector_id_fkey"
FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("id");

-- 5. RD Projects -> Institutions
-- Create missing 'institutions' table referenced by rd_projects
CREATE TABLE IF NOT EXISTS "public"."institutions" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "name_en" text NOT NULL,
    "name_ar" text,
    "logo_url" text,
    "website" text,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    CONSTRAINT "institutions_pkey" PRIMARY KEY ("id")
);

-- Enable RLS
ALTER TABLE "public"."institutions" ENABLE ROW LEVEL SECURITY;

-- Add RLS Policy
CREATE POLICY "Enable read access for all users" ON "public"."institutions"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Add ForeignKey
ALTER TABLE "public"."rd_projects"
ADD CONSTRAINT "rd_projects_institution_id_fkey"
FOREIGN KEY ("institution_id") REFERENCES "public"."institutions"("id");
