-- Insert seed/official templates
INSERT INTO strategic_plans (
  name_en, name_ar, description_en, description_ar,
  is_template, is_public, is_featured, template_type, template_category,
  template_tags, usage_count, template_rating, template_reviews,
  status, vision_en, vision_ar, mission_en, mission_ar,
  objectives, kpis, swot, stakeholders, risks,
  governance, communication_plan, change_management,
  start_year, end_year, owner_email
) VALUES 
-- 1. Digital Transformation Template
(
  'Digital Transformation Strategy', 'استراتيجية التحول الرقمي',
  'Comprehensive template for government digital transformation initiatives including e-services, data governance, and citizen engagement platforms.',
  'قالب شامل لمبادرات التحول الرقمي الحكومي بما في ذلك الخدمات الإلكترونية وحوكمة البيانات ومنصات مشاركة المواطنين.',
  true, true, true, 'digital_transformation', 'system',
  ARRAY['digital', 'transformation', 'e-services', 'technology', 'automation'],
  0, 4.5, 12, 'template',
  'To become a leading digital government delivering seamless citizen services',
  'أن نصبح حكومة رقمية رائدة تقدم خدمات سلسة للمواطنين',
  'Enabling digital excellence through innovative technology solutions',
  'تمكين التميز الرقمي من خلال الحلول التقنية المبتكرة',
  '[{"id":"obj-1","title_en":"Digitize 80% of services","title_ar":"رقمنة 80% من الخدمات","priority":"high"},{"id":"obj-2","title_en":"Implement unified digital platform","title_ar":"تنفيذ منصة رقمية موحدة","priority":"high"},{"id":"obj-3","title_en":"Achieve 90% citizen satisfaction","title_ar":"تحقيق رضا المواطنين 90%","priority":"medium"}]'::jsonb,
  '[{"id":"kpi-1","name_en":"Digital service adoption rate","name_ar":"معدل تبني الخدمات الرقمية","target":80,"unit":"percent"},{"id":"kpi-2","name_en":"Average transaction time","name_ar":"متوسط وقت المعاملة","target":5,"unit":"minutes"}]'::jsonb,
  '{"strengths":["Existing IT infrastructure","Skilled workforce"],"weaknesses":["Legacy systems","Change resistance"],"opportunities":["Government support","Tech partnerships"],"threats":["Cybersecurity risks","Budget constraints"]}'::jsonb,
  '[{"name":"IT Department","type":"internal","influence":"high","interest":"high"},{"name":"Citizens","type":"citizen","influence":"medium","interest":"high"}]'::jsonb,
  '[{"category":"technology","description":"System integration failures","probability":"medium","impact":"high","mitigation":"Phased rollout approach"}]'::jsonb,
  '{"structure":[{"role":"Digital Transformation Officer","responsibilities":["Strategy oversight","Stakeholder management"]}],"committees":[{"name":"Digital Steering Committee","frequency":"monthly"}]}'::jsonb,
  '{"internal_channels":["Email","Intranet","Town halls"],"external_channels":["Website","Social media","Press releases"],"key_messages":["Digital first","Citizen-centric"]}'::jsonb,
  '{"readiness_assessment":"Moderate readiness with training needs","change_approach":"Phased adoption with champions","training_plan":[{"topic":"Digital tools","audience":"All staff","duration":"2 days"}]}'::jsonb,
  2024, 2029, 'system@momah.gov.sa'
),
-- 2. Sustainability Strategy Template
(
  'Sustainability & Green Initiative', 'مبادرة الاستدامة والبيئة الخضراء',
  'Environmental sustainability framework for municipalities focusing on carbon reduction, waste management, and green infrastructure.',
  'إطار الاستدامة البيئية للبلديات مع التركيز على تقليل الكربون وإدارة النفايات والبنية التحتية الخضراء.',
  true, true, true, 'sustainability', 'system',
  ARRAY['sustainability', 'environment', 'green', 'carbon', 'waste', 'renewable'],
  0, 4.7, 8, 'template',
  'A sustainable municipality leading environmental excellence',
  'بلدية مستدامة رائدة في التميز البيئي',
  'Protecting our environment for future generations through sustainable practices',
  'حماية بيئتنا للأجيال القادمة من خلال الممارسات المستدامة',
  '[{"id":"obj-1","title_en":"Reduce carbon emissions by 30%","title_ar":"تقليل انبعاثات الكربون بنسبة 30%","priority":"high"},{"id":"obj-2","title_en":"Achieve 50% waste recycling rate","title_ar":"تحقيق معدل إعادة تدوير 50%","priority":"high"}]'::jsonb,
  '[{"id":"kpi-1","name_en":"Carbon footprint reduction","name_ar":"تقليل البصمة الكربونية","target":30,"unit":"percent"},{"id":"kpi-2","name_en":"Recycling rate","name_ar":"معدل إعادة التدوير","target":50,"unit":"percent"}]'::jsonb,
  '{"strengths":["Community awareness","Government mandates"],"weaknesses":["Initial investment costs"],"opportunities":["Green financing","Tech innovations"],"threats":["Climate change acceleration"]}'::jsonb,
  '[{"name":"Environment Ministry","type":"government","influence":"high","interest":"high"},{"name":"Local businesses","type":"private","influence":"medium","interest":"medium"}]'::jsonb,
  '[{"category":"financial","description":"Funding shortfall","probability":"medium","impact":"high","mitigation":"Diversified funding sources"}]'::jsonb,
  '{"structure":[{"role":"Sustainability Director","responsibilities":["Environmental oversight","Compliance"]}]}'::jsonb,
  '{"internal_channels":["Green newsletters","Workshops"],"external_channels":["Community events","Social media campaigns"]}'::jsonb,
  '{"readiness_assessment":"Growing environmental awareness","change_approach":"Community-led initiatives","training_plan":[{"topic":"Sustainability practices","audience":"Operations staff"}]}'::jsonb,
  2024, 2030, 'system@momah.gov.sa'
),
-- 3. Smart City Template
(
  'Smart City Development Strategy', 'استراتيجية تطوير المدينة الذكية',
  'Comprehensive smart city framework covering IoT infrastructure, data analytics, intelligent transportation, and connected services.',
  'إطار شامل للمدينة الذكية يغطي البنية التحتية لإنترنت الأشياء وتحليلات البيانات والنقل الذكي والخدمات المتصلة.',
  true, true, true, 'smart_city', 'system',
  ARRAY['smart city', 'IoT', 'sensors', 'data', 'AI', 'transportation', 'connected'],
  0, 4.6, 10, 'template',
  'Building an intelligent, connected city that enhances quality of life',
  'بناء مدينة ذكية متصلة تعزز جودة الحياة',
  'Leveraging technology to create efficient, sustainable, and livable urban environments',
  'الاستفادة من التكنولوجيا لخلق بيئات حضرية فعالة ومستدامة وصالحة للعيش',
  '[{"id":"obj-1","title_en":"Deploy city-wide IoT sensor network","title_ar":"نشر شبكة أجهزة استشعار على مستوى المدينة","priority":"high"},{"id":"obj-2","title_en":"Implement smart traffic management","title_ar":"تنفيذ إدارة المرور الذكية","priority":"high"}]'::jsonb,
  '[{"id":"kpi-1","name_en":"IoT sensors deployed","name_ar":"أجهزة الاستشعار المنشورة","target":10000,"unit":"devices"},{"id":"kpi-2","name_en":"Traffic congestion reduction","name_ar":"تقليل الازدحام المروري","target":25,"unit":"percent"}]'::jsonb,
  '{"strengths":["Modern infrastructure","Tech-savvy population"],"weaknesses":["High implementation costs","Data privacy concerns"],"opportunities":["5G rollout","AI advancements"],"threats":["Cybersecurity","Technology obsolescence"]}'::jsonb,
  '[{"name":"Telecom providers","type":"private","influence":"high","interest":"high"},{"name":"Residents","type":"citizen","influence":"medium","interest":"high"}]'::jsonb,
  '[{"category":"technology","description":"System interoperability issues","probability":"high","impact":"medium","mitigation":"Open standards adoption"}]'::jsonb,
  '{"structure":[{"role":"Smart City Director","responsibilities":["Technology integration","Innovation management"]}]}'::jsonb,
  '{"internal_channels":["Tech updates","Innovation forums"],"external_channels":["Smart city app","Digital displays"]}'::jsonb,
  '{"readiness_assessment":"High digital literacy","change_approach":"Technology showcases and pilots","training_plan":[{"topic":"IoT platforms","audience":"Technical teams"}]}'::jsonb,
  2024, 2030, 'system@momah.gov.sa'
),
-- 4. Citizen Services Excellence Template
(
  'Citizen Services Excellence Strategy', 'استراتيجية التميز في خدمات المواطنين',
  'Framework for transforming citizen services through service design, omnichannel delivery, and continuous improvement.',
  'إطار لتحويل خدمات المواطنين من خلال تصميم الخدمات والتسليم متعدد القنوات والتحسين المستمر.',
  true, true, true, 'citizen_services', 'system',
  ARRAY['citizen', 'services', 'customer experience', 'omnichannel', 'satisfaction'],
  0, 4.8, 15, 'template',
  'Delivering exceptional citizen experiences at every touchpoint',
  'تقديم تجارب استثنائية للمواطنين في كل نقطة تواصل',
  'Putting citizens at the center of service design and delivery',
  'وضع المواطنين في قلب تصميم وتقديم الخدمات',
  '[{"id":"obj-1","title_en":"Achieve 95% citizen satisfaction","title_ar":"تحقيق رضا المواطنين 95%","priority":"high"},{"id":"obj-2","title_en":"Reduce service delivery time by 50%","title_ar":"تقليل وقت تقديم الخدمة بنسبة 50%","priority":"high"}]'::jsonb,
  '[{"id":"kpi-1","name_en":"Citizen satisfaction score","name_ar":"درجة رضا المواطنين","target":95,"unit":"percent"},{"id":"kpi-2","name_en":"First contact resolution","name_ar":"حل من أول تواصل","target":80,"unit":"percent"}]'::jsonb,
  '{"strengths":["Dedicated staff","Clear service standards"],"weaknesses":["Siloed departments","Manual processes"],"opportunities":["Digital channels","AI chatbots"],"threats":["Rising expectations","Resource constraints"]}'::jsonb,
  '[{"name":"Service center staff","type":"internal","influence":"medium","interest":"high"},{"name":"Citizens","type":"citizen","influence":"high","interest":"high"}]'::jsonb,
  '[{"category":"operational","description":"Service disruption during transition","probability":"medium","impact":"high","mitigation":"Parallel running period"}]'::jsonb,
  '{"structure":[{"role":"Chief Experience Officer","responsibilities":["Service excellence","Citizen feedback"]}]}'::jsonb,
  '{"internal_channels":["Service updates","Best practices sharing"],"external_channels":["Citizen portal","Mobile app","Social media"]}'::jsonb,
  '{"readiness_assessment":"Staff committed to improvement","change_approach":"Service design workshops","training_plan":[{"topic":"Customer service excellence","audience":"Frontline staff"}]}'::jsonb,
  2024, 2028, 'system@momah.gov.sa'
),
-- 5. Innovation & R&D Strategy Template
(
  'Innovation & R&D Strategy', 'استراتيجية الابتكار والبحث والتطوير',
  'Framework for establishing innovation culture, R&D partnerships, and pilot program management.',
  'إطار لتأسيس ثقافة الابتكار وشراكات البحث والتطوير وإدارة البرامج التجريبية.',
  true, true, true, 'innovation', 'system',
  ARRAY['innovation', 'R&D', 'pilots', 'startups', 'incubation', 'experimentation'],
  0, 4.4, 6, 'template',
  'Becoming a hub for municipal innovation and experimentation',
  'أن نصبح مركزاً للابتكار والتجريب البلدي',
  'Fostering innovation through partnerships, pilots, and continuous learning',
  'تعزيز الابتكار من خلال الشراكات والتجارب والتعلم المستمر',
  '[{"id":"obj-1","title_en":"Launch 10 innovation pilots annually","title_ar":"إطلاق 10 مشاريع تجريبية سنوياً","priority":"high"},{"id":"obj-2","title_en":"Establish innovation lab","title_ar":"إنشاء مختبر الابتكار","priority":"high"}]'::jsonb,
  '[{"id":"kpi-1","name_en":"Pilots launched","name_ar":"المشاريع التجريبية المطلقة","target":10,"unit":"count"},{"id":"kpi-2","name_en":"Pilot success rate","name_ar":"معدل نجاح التجارب","target":60,"unit":"percent"}]'::jsonb,
  '{"strengths":["Leadership support","Funding availability"],"weaknesses":["Risk aversion","Bureaucratic processes"],"opportunities":["Startup ecosystem","Global best practices"],"threats":["Failed pilots impact","Resource diversion"]}'::jsonb,
  '[{"name":"Universities","type":"academia","influence":"medium","interest":"high"},{"name":"Startups","type":"private","influence":"medium","interest":"high"}]'::jsonb,
  '[{"category":"strategic","description":"Innovation fatigue","probability":"medium","impact":"medium","mitigation":"Celebrate wins, learn from failures"}]'::jsonb,
  '{"structure":[{"role":"Chief Innovation Officer","responsibilities":["Innovation strategy","Partnership management"]}]}'::jsonb,
  '{"internal_channels":["Innovation newsletter","Hackathons"],"external_channels":["Innovation portal","Partner network"]}'::jsonb,
  '{"readiness_assessment":"Growing innovation appetite","change_approach":"Quick wins to build momentum","training_plan":[{"topic":"Design thinking","audience":"All departments"}]}'::jsonb,
  2024, 2029, 'system@momah.gov.sa'
)
ON CONFLICT DO NOTHING;