-- Insert Saudi Universities as Organizations
-- Using correct column name 'type' instead of 'org_type'

INSERT INTO organizations (name_en, name_ar, type, website, is_active, is_verified) VALUES
-- Top Public Universities
('King Saud University', 'جامعة الملك سعود', 'university', 'https://ksu.edu.sa', true, true),
('King Abdullah University of Science and Technology', 'جامعة الملك عبدالله للعلوم والتقنية', 'university', 'https://kaust.edu.sa', true, true),
('King AbdulAziz University', 'جامعة الملك عبدالعزيز', 'university', 'https://kau.edu.sa', true, true),
('King Fahd University of Petroleum and Minerals', 'جامعة الملك فهد للبترول والمعادن', 'university', 'https://kfupm.edu.sa', true, true),
('Umm Al-Qura University', 'جامعة أم القرى', 'university', 'https://uqu.edu.sa', true, true),
('Al-Imam Muhammad Ibn Saud Islamic University', 'جامعة الإمام محمد بن سعود الإسلامية', 'university', 'https://imamu.edu.sa', true, true),
('King Faisal University', 'جامعة الملك فيصل', 'university', 'https://kfu.edu.sa', true, true),
('Qassim University', 'جامعة القصيم', 'university', 'https://qu.edu.sa', true, true),
('Imam Abdulrahman Bin Faisal University', 'جامعة الإمام عبدالرحمن بن فيصل', 'university', 'https://iau.edu.sa', true, true),
('Islamic University of Madinah', 'الجامعة الإسلامية بالمدينة المنورة', 'university', 'https://iu.edu.sa', true, true),
('Taibah University', 'جامعة طيبة', 'university', 'https://taibahu.edu.sa', true, true),
('King Khalid University', 'جامعة الملك خالد', 'university', 'https://kku.edu.sa', true, true),
('Princess Nora bint Abdulrahman University', 'جامعة الأميرة نورة بنت عبدالرحمن', 'university', 'https://pnu.edu.sa', true, true),
('Taif University', 'جامعة الطائف', 'university', 'https://tu.edu.sa', true, true),
('Jazan University', 'جامعة جازان', 'university', 'https://jazanu.edu.sa', true, true),
('Prince Sattam Bin Abdulaziz University', 'جامعة الأمير سطام بن عبدالعزيز', 'university', 'https://psau.edu.sa', true, true),
('Majmaah University', 'جامعة المجمعة', 'university', 'https://mu.edu.sa', true, true),
('University of Jeddah', 'جامعة جدة', 'university', 'https://uj.edu.sa', true, true),
('King Saud bin Abdulaziz University for Health Sciences', 'جامعة الملك سعود بن عبدالعزيز للعلوم الصحية', 'university', 'https://ksau-hs.edu.sa', true, true),
('University of Hail', 'جامعة حائل', 'university', 'https://uoh.edu.sa', true, true),
('Najran University', 'جامعة نجران', 'university', 'https://nu.edu.sa', true, true),
('Al Jouf University', 'جامعة الجوف', 'university', 'https://ju.edu.sa', true, true),
('University of Tabuk', 'جامعة تبوك', 'university', 'https://ut.edu.sa', true, true),
('Shaqra University', 'جامعة شقراء', 'university', 'https://su.edu.sa', true, true),
('Northern Borders University', 'جامعة الحدود الشمالية', 'university', 'https://nbu.edu.sa', true, true),
('Al Baha University', 'جامعة الباحة', 'university', 'https://bu.edu.sa', true, true),
('University of Hafr Al Batin', 'جامعة حفر الباطن', 'university', 'https://uhb.edu.sa', true, true),
('University of Bisha', 'جامعة بيشة', 'university', 'https://ub.edu.sa', true, true),
-- Private Universities
('Alfaisal University', 'جامعة الفيصل', 'university', 'https://alfaisal.edu', true, true),
('Prince Sultan University', 'جامعة الأمير سلطان', 'university', 'https://psu.edu.sa', true, true),
('Prince Mohammad Bin Fahd University', 'جامعة الأمير محمد بن فهد', 'university', 'https://pmu.edu.sa', true, true),
('Effat University', 'جامعة عفت', 'university', 'https://effatuniversity.edu.sa', true, true),
('Al Maarefa University', 'جامعة المعرفة', 'university', 'https://mcst.edu.sa', true, true),
('Dar Al-Hekma University', 'جامعة دار الحكمة', 'university', 'https://dah.edu.sa', true, true),
('Al Yamamah University', 'جامعة اليمامة', 'university', 'https://yu.edu.sa', true, true),
('Fahad Bin Sultan University', 'جامعة فهد بن سلطان', 'university', 'https://fbsu.edu.sa', true, true),
('Dar Al Uloom University', 'جامعة دار العلوم', 'university', 'https://dau.edu.sa', true, true),
('Riyadh Elm University', 'جامعة رياض العلم', 'university', 'https://riyadh.edu.sa', true, true),
('Sulaiman Al Rajhi University', 'جامعة سليمان الراجحي', 'university', 'https://sr.edu.sa', true, true),
('University of Prince Mugrin', 'جامعة الأمير مقرن', 'university', 'https://upm.edu.sa', true, true),
('University of Business and Technology', 'جامعة الأعمال والتقنية', 'university', 'https://ubt.edu.sa', true, true),
('Mustaqbal University', 'جامعة المستقبل', 'university', 'https://mustaqbal.edu.sa', true, true),
-- Research Institutions
('Institute of Public Administration', 'معهد الإدارة العامة', 'research_center', 'https://ipa.edu.sa', true, true),
('King Abdulaziz City for Science and Technology', 'مدينة الملك عبدالعزيز للعلوم والتقنية', 'research_center', 'https://kacst.edu.sa', true, true)
ON CONFLICT DO NOTHING;

-- Add auto-approval rules for researchers from Saudi universities
INSERT INTO auto_approval_rules (persona_type, rule_type, rule_value, role_to_assign, priority, is_active) VALUES
('researcher', 'email_domain', 'ksu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'kaust.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'kau.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'kfupm.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'uqu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'imamu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'kfu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'qu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'iau.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'iu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'taibahu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'kku.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'pnu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'tu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'jazanu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'psau.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'mu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'uj.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'ksau-hs.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'uoh.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'nu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'ju.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'ut.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'su.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'nbu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'bu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'uhb.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'ub.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'alfaisal.edu', 'researcher', 10, true),
('researcher', 'email_domain', 'psu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'pmu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'effatuniversity.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'dah.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'yu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'fbsu.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'dau.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'riyadh.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'sr.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'upm.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'ubt.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'ipa.edu.sa', 'researcher', 10, true),
('researcher', 'email_domain', 'kacst.edu.sa', 'researcher', 10, true)
ON CONFLICT DO NOTHING;